### Creation d'un user
POST http://localhost:1818/api/auth/register
Content-Type: application/json

{
    "firstname": "Admin",
    "lastname": "Test",
    "email": "admin.test@example.com",
    "password": "mdpadmintest"
}

### Creation d'un user
POST http://localhost:1818/api/auth/register
Content-Type: application/json

{
    "firstname": "Thomas",
    "lastname": "Payet",
    "email": "thomaspayet.tp@example.com",
    "password": "Adminmdp974!"
}


### Connexion d'un user
POST http://localhost:1818/api/auth/login
Content-Type: application/json

{
    "email" : "admin.test@example.com",
    "password": "mdpadmintest"
}
